// <auto-generated />
using System;
using GraphQL_Project.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GraphQL_Project.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GraphQL_Project.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Appetizer"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Main Coarse"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Dessert"
                        });
                });

            modelBuilder.Entity("GraphQL_Project.Models.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "test1",
                            ImageUrl = "test1",
                            Name = "item1",
                            Price = 9.99m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "test2",
                            ImageUrl = "test2",
                            Name = "item2",
                            Price = 10.99m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "test3",
                            ImageUrl = "test3",
                            Name = "item3",
                            Price = 11.99m
                        });
                });

            modelBuilder.Entity("GraphQL_Project.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PartySize")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SpecialRequest")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerName = "name1",
                            Email = "email1",
                            PartySize = 4,
                            PhoneNumber = "ph1",
                            ReservationDate = new DateTime(2024, 7, 23, 21, 3, 53, 832, DateTimeKind.Utc).AddTicks(1818),
                            SpecialRequest = "none"
                        },
                        new
                        {
                            Id = 2,
                            CustomerName = "name2",
                            Email = "email2",
                            PartySize = 5,
                            PhoneNumber = "ph2",
                            ReservationDate = new DateTime(2024, 7, 23, 22, 3, 53, 832, DateTimeKind.Utc).AddTicks(1823),
                            SpecialRequest = "Something"
                        },
                        new
                        {
                            Id = 3,
                            CustomerName = "name3",
                            Email = "email3",
                            PartySize = 6,
                            PhoneNumber = "ph3",
                            ReservationDate = new DateTime(2024, 7, 23, 23, 3, 53, 832, DateTimeKind.Utc).AddTicks(1832),
                            SpecialRequest = "none"
                        });
                });

            modelBuilder.Entity("GraphQL_Project.Models.Menu", b =>
                {
                    b.HasOne("GraphQL_Project.Models.Category", null)
                        .WithMany("Menus")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GraphQL_Project.Models.Category", b =>
                {
                    b.Navigation("Menus");
                });
#pragma warning restore 612, 618
        }
    }
}
